### ISSUE TITLE
ValueError: Input X must be non-negative

### ISSUE THREAD

**Issue by eddyirwan** [Poyuli/sentiment.analysis#1]
Vectorizing review 24000 of 25000
Traceback (most recent call last):
  File "sentiment.py", line 349, in <module>
    elif training_model == "NB":
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1433, in cross_val_score
    for train, test in cv)
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py", line 1531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/naive_bayes.py", line 552, in fit
    self._count(X, Y)
  File "/Users/eddyirwan/anaconda/lib/python2.7/site-packages/sklearn/naive_bayes.py", line 655, in _count
    raise ValueError("Input X must be non-negative")
ValueError: Input X must be non-negative

[sentiment.py.zip](https://github.com/Poyuli/sentiment.analysis/files/881150/sentiment.py.zip)

**Comment by somiyaa** [comment]
hi eddyirwan

are you able to run this code without getting any error ?

**Comment by Shyamasundar** [comment]
Yeah

**Comment by somiyaa** [comment]
thanks for replying @Shyamasundar !
I just ran it again. dint get any error. :)

**Comment by Shyamasundar** [comment]
Welcome

**Comment by somiyaa** [comment]
hi  Shyamasundar 
can you please tell me number positive and negative reviews in training and testing datasets and also the number of unigrams, bigrams and unigram/bigrams extracted while preprocessing ?

**Comment by Anand-s-cmd** [comment]
Can anyone help me with this please I am importing CSV file and working on data set which has 32 columns in that one column is having -1 values, it is throwing me an error while selecting the features?
ERROR: **_raise ValueError("Input X must be non-negative.")_**

import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
bank = pd.read_csv("bank_data.csv")
X = bank.iloc[:,0:31]  #independent columns
y = bank.iloc[:,-1]    #target column i.e price range
#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)
